# Auto-generated by scripts/run_synth.tcl — program Cora Z7
open_hw_manager
connect_hw_server
open_hw_target
current_hw_device [lindex [get_hw_devices] 0]
refresh_hw_device [current_hw_device]
set_property PROGRAM.FILE {C:/Users/onepl/Desktop/systolic-array-workshop/fpga/project/systolic_array.runs/impl_1/block_design_wrapper.bit} [current_hw_device]
program_hw_devices [current_hw_device]
puts "Programmed: C:/Users/onepl/Desktop/systolic-array-workshop/fpga/project/systolic_array.runs/impl_1/block_design_wrapper.bit"
