# Vivado synthesis / implementation for Digilent Cora Z7-07S
# Usage (from repo root):
#   vivado -mode batch -source scripts/run_synth.tcl
#
# Requires Vivado with Zynq-7000 + Digilent board files at:
#   C:/Xilinx/vivado-boards/new/board_files

set script_dir  [file dirname [file normalize [info script]]]
set root_dir    [file normalize [file join $script_dir ..]]
set project_dir [file join $root_dir fpga project]
set rtl_dir     [file join $root_dir rtl]
set fpga_dir    [file join $root_dir fpga]

set part       "xc7z007sclg400-1"
set board_part "digilentinc.com:cora-z7-07s:part0:1.1"
set board_repo "C:/Xilinx/vivado-boards/new/board_files"
set design_name block_design

# Digilent board definitions
set_param board.repoPaths [list $board_repo]

file mkdir $project_dir
create_project systolic_array $project_dir -part $part -force

# Prefer board part when available (falls back to silicon part only)
if {[catch {set_property board_part $board_part [current_project]} err]} {
    puts "WARNING: board_part '$board_part' not applied: $err"
    puts "         Continuing with part $part only — check BOARD.REPO_PATHS."
}

# RTL — portable IP + AXI wrapper (SV) + Verilog BD shell
set rtl_files [lsort [concat \
    [glob -nocomplain [file join $rtl_dir *.sv]] \
    [glob -nocomplain [file join $rtl_dir *.v]]]]
if {[llength $rtl_files] == 0} {
    error "No RTL .sv/.v files found in $rtl_dir"
}
add_files -norecurse $rtl_files
# Ensure BD shell is treated as Verilog (required for module reference top)
set bd_shell [get_files -quiet axi_wrapper_bd.v]
if {$bd_shell ne ""} {
    set_property file_type {Verilog} $bd_shell
}
update_compile_order -fileset sources_1

# Constraints (PS-centric)
add_files -fileset constrs_1 [file join $fpga_dir constraints.xdc]

# Block design: PS7 + reset + interconnect + axi_wrapper @ 0x43C0_0000
source [file join $fpga_dir block_design.tcl]

# Make BD wrapper the top
set bd_file [lindex [get_files *.bd] 0]
if {$bd_file eq ""} {
    error "No block design (.bd) found after sourcing block_design.tcl"
}
set wrapper_file [make_wrapper -files $bd_file -top]
add_files -norecurse $wrapper_file
set_property top ${design_name}_wrapper [current_fileset]
update_compile_order -fileset sources_1

proc check_run_ok {run_name} {
    set prog [get_property PROGRESS [get_runs $run_name]]
    set status [get_property STATUS [get_runs $run_name]]
    puts "Run $run_name: PROGRESS=$prog STATUS=$status"
    if {$prog ne "100%"} {
        error "Run $run_name did not complete (PROGRESS=$prog STATUS=$status)"
    }
    # Fail on synth/impl errors in status string
    if {[string match -nocase "*ERROR*" $status] || [string match -nocase "*fail*" $status]} {
        if {![string match -nocase "*Complete*" $status]} {
            error "Run $run_name failed: $status"
        }
    }
}

# Synthesis
launch_runs synth_1 -jobs 4
wait_on_run synth_1
check_run_ok synth_1
open_run synth_1
report_utilization -file [file join $project_dir utilization_synth.rpt]
puts "=== Synthesis Utilization ==="
set fp [open [file join $project_dir utilization_synth.rpt] r]
puts [read $fp]
close $fp

# Implementation + bitstream
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
check_run_ok impl_1
open_run impl_1
report_timing_summary -file [file join $project_dir timing.rpt]
puts "=== Timing Summary ==="
set fp [open [file join $project_dir timing.rpt] r]
set timing_txt [read $fp]
close $fp
puts $timing_txt

# Bitstream path
set bitfile [file join $project_dir systolic_array.runs impl_1 ${design_name}_wrapper.bit]
if {![file exists $bitfile]} {
    set bits [glob -nocomplain [file join $project_dir systolic_array.runs impl_1 *.bit]]
    if {[llength $bits] == 0} {
        error "No bitstream produced under impl_1"
    }
    set bitfile [lindex $bits 0]
}

# Emit program.tcl for Hardware Manager
set prog_tcl [file join $fpga_dir program.tcl]
set fp [open $prog_tcl w]
puts $fp "# Auto-generated by scripts/run_synth.tcl — program Cora Z7"
puts $fp "open_hw_manager"
puts $fp "connect_hw_server"
puts $fp "open_hw_target"
puts $fp "current_hw_device \[lindex \[get_hw_devices\] 0\]"
puts $fp "refresh_hw_device \[current_hw_device\]"
puts $fp "set_property PROGRAM.FILE {$bitfile} \[current_hw_device\]"
puts $fp "program_hw_devices \[current_hw_device\]"
puts $fp "puts \"Programmed: $bitfile\""
close $fp

puts "=== Build complete ==="
puts "Bitstream: $bitfile"
puts "Program:   vivado -mode batch -source $prog_tcl"
