`timescale 1ns / 1ps

// Testbench for the 4x4 systolic array (Stages 2 and 3).
// Reads test cases from tb/test_vectors/*.txt (generated by golden_model.py).
// Writes results to tb/test_vectors/results.json for Python to check.

module tb_systolic_array (
    input logic clk
);

    localparam int N      = 4;
    localparam int DATA_W = 8;
    localparam int ACC_W  = 32;
    localparam int MAX_CASES = 128;
    localparam string VECTORS_DIR = "../tb/test_vectors/";
    localparam string MANIFEST    = "../tb/test_vectors/manifest.list";
    localparam string RESULTS     = "../tb/test_vectors/results.json";

    logic                  rst;
    logic                  start;
    logic                  done;
    logic signed [DATA_W-1:0] a_load [N][N];
    logic signed [DATA_W-1:0] b_load [N][N];
    logic signed [ACC_W-1:0]  c_out  [N][N];

    top #(
        .N     (N),
        .DATA_W(DATA_W),
        .ACC_W (ACC_W)
    ) dut (
        .clk   (clk),
        .rst   (rst),
        .start (start),
        .done  (done),
        .a_load(a_load),
        .b_load(b_load),
        .c_out (c_out)
    );

    string case_names [MAX_CASES];
    int    case_count;
    int    errors;
    string line;
    logic signed [ACC_W-1:0] c_results [MAX_CASES][N][N];

    task automatic load_case_file(input string filename, output string cname);
        int file;
        int i, j;
        string tag;
        int val;

        file = $fopen(filename, "r");
        if (file == 0) begin
            $display("ERROR: cannot open %s", filename);
            cname = "";
            return;
        end

        // name line
        void'($fscanf(file, "name %s\n", cname));

        // A matrix
        void'($fscanf(file, "%s\n", tag));
        for (i = 0; i < N; i++)
            for (j = 0; j < N; j++) begin
                void'($fscanf(file, "%d", val));
                a_load[i][j] = val;
            end

        // B matrix
        void'($fscanf(file, "%s\n", tag));
        for (i = 0; i < N; i++)
            for (j = 0; j < N; j++) begin
                void'($fscanf(file, "%d", val));
                b_load[i][j] = val;
            end

        $fclose(file);
    endtask

    task automatic run_one_case(input int ci, input string cname);
        int timeout;
        int i, j;
        logic signed [ACC_W-1:0] c_snap [N][N];

        @(posedge clk);
        start = 1;
        repeat (2) @(posedge clk);
        start = 0;

        timeout = 0;
        while (!done && timeout < 50) begin
            @(posedge clk);
            timeout++;
        end

        if (!done) begin
            $display("FAIL [%s]: timeout", cname);
            errors++;
        end else begin
            // pe_en must be low after done (contract: hold, no further MAC)
            if (dut.u_controller.pe_en !== 1'b0) begin
                $display("FAIL [%s]: pe_en still high after done", cname);
                errors++;
            end

            for (i = 0; i < N; i++)
                for (j = 0; j < N; j++) begin
                    c_results[ci][i][j] = c_out[i][j];
                    c_snap[i][j] = c_out[i][j];
                end

            // Post-done stability: many idle cycles, then re-read unchanged
            repeat (20) @(posedge clk);
            if (dut.u_controller.pe_en !== 1'b0) begin
                $display("FAIL [%s]: pe_en rose during idle", cname);
                errors++;
            end
            for (i = 0; i < N; i++)
                for (j = 0; j < N; j++)
                    if (c_out[i][j] !== c_snap[i][j]) begin
                        $display("FAIL [%s]: c_out[%0d][%0d] changed after idle (%0d -> %0d)",
                                 cname, i, j, c_snap[i][j], c_out[i][j]);
                        errors++;
                    end

            $display("PASS [%s]: done + stability", cname);
        end
    endtask

    task automatic write_results();
        int f;
        int ci, i, j;

        f = $fopen(RESULTS, "w");
        $fwrite(f, "{\n  \"results\": [\n");
        for (ci = 0; ci < case_count; ci++) begin
            $fwrite(f, "    {\"name\": \"%s\", \"C\": [", case_names[ci]);
            for (i = 0; i < N; i++) begin
                $fwrite(f, "[");
                for (j = 0; j < N; j++) begin
                    $fwrite(f, "%0d", c_results[ci][i][j]);
                    if (j < N - 1) $fwrite(f, ", ");
                end
                $fwrite(f, "]");
                if (i < N - 1) $fwrite(f, ", ");
            end
            $fwrite(f, "]}");
            if (ci < case_count - 1) $fwrite(f, ",");
            $fwrite(f, "\n");
        end
        $fwrite(f, "  ]\n}\n");
        $fclose(f);
        $display("Wrote results to %s", RESULTS);
    endtask

    initial begin
        int manifest_file;
        string case_file;
        string cname;

        errors = 0;
        case_count = 0;
        rst = 1;
        start = 0;

        repeat (3) @(posedge clk);
        rst = 0;

        // Fixed single-case mode: identity test (used by `make array`)
        if (!$test$plusargs("full")) begin
            $display("Running fixed identity test case");
            for (int i = 0; i < N; i++)
                for (int j = 0; j < N; j++) begin
                    a_load[i][j] = (i == j) ? 8'sd1 : 8'sd0;
                    b_load[i][j] = (i == j) ? 8'sd1 : 8'sd0;
                end
            case_names[0] = "identity";
            case_count = 1;
            run_one_case(0, "identity");
        end else begin
            // Full randomized mode: read manifest.list
            manifest_file = $fopen(MANIFEST, "r");
            if (manifest_file == 0) begin
                $display("ERROR: run python tb/golden_model.py generate first");
                $finish(1);
            end

            while ($fscanf(manifest_file, "%s", cname) == 1 && case_count < MAX_CASES) begin
                case_names[case_count] = cname;
                case_file = {VECTORS_DIR, cname, ".txt"};
                load_case_file(case_file, cname);
                $display("Running case: %s", cname);
                run_one_case(case_count, cname);
                case_count++;
            end
            $fclose(manifest_file);
        end

        write_results();
        $display("=== tb_systolic_array: simulation complete (%0d cases) ===", case_count);
        $finish;
    end

    // Dump waveforms when +trace is passed
    initial begin
        if ($test$plusargs("trace"))
            $dumpvars(0, tb_systolic_array);
    end

endmodule
